root = "."
testdata_dir = "fixtures/testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["serve"]
  bin = "./tmp/rtnl"
  cmd = "go build -o ./tmp/rtnl ./cmd/rtnl"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata", "fixtures", "node_modules"]
  exclude_file = ["yarn.lock", "package-lock.json"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "js", "css"]
  include_file = [".env"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false